// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBtlqIJ9dUO6aSI-SRN5xRpD5BdyG_qG4',
    appId: '1:209401212937:web:cf64c7950cb4477c2688d8',
    messagingSenderId: '209401212937',
    projectId: 'zoom-module',
    authDomain: 'zoom-module.firebaseapp.com',
    databaseURL: 'https://zoom-module-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zoom-module.firebasestorage.app',
    measurementId: 'G-Y454SJ41X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYKZ0-JyMdanb4EauQYJ9wYk01Xj6YbaU',
    appId: '1:209401212937:android:0964dee8d3cf28ce2688d8',
    messagingSenderId: '209401212937',
    projectId: 'zoom-module',
    databaseURL: 'https://zoom-module-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zoom-module.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIqBGeb4a7ZWoOP2yNMi7-kMXeGXbYQDI',
    appId: '1:209401212937:ios:b718dfc199a28b032688d8',
    messagingSenderId: '209401212937',
    projectId: 'zoom-module',
    databaseURL: 'https://zoom-module-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zoom-module.firebasestorage.app',
    iosBundleId: 'com.zoommain.zoommainproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIqBGeb4a7ZWoOP2yNMi7-kMXeGXbYQDI',
    appId: '1:209401212937:ios:b718dfc199a28b032688d8',
    messagingSenderId: '209401212937',
    projectId: 'zoom-module',
    databaseURL: 'https://zoom-module-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zoom-module.firebasestorage.app',
    iosBundleId: 'com.zoommain.zoommainproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBtlqIJ9dUO6aSI-SRN5xRpD5BdyG_qG4',
    appId: '1:209401212937:web:e646d29899b880462688d8',
    messagingSenderId: '209401212937',
    projectId: 'zoom-module',
    authDomain: 'zoom-module.firebaseapp.com',
    databaseURL: 'https://zoom-module-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zoom-module.firebasestorage.app',
    measurementId: 'G-4WY3LYH77G',
  );
}
